smartlyio/oats

src/runtime.ts, test/runtime.spec.ts
Currently an error is thrown if an object with an optional property is created with that property as `undefined`.
With this PR, the property will be ignored if its missing (old behaviour) or if the value is undefined.
=> Ignore properties if they are present but their value is undefined

README.md, examples/client.ts, examples/driver.ts, examples/server.ts, package.json, src/client.ts, src/generate-server.ts, src/generate-types.ts, src/runtime.ts, src/server.ts, src/util.ts, test/example.yaml, test/runtime.spec.ts, test/server.spec.ts
We expose only the headers specified in the oa spec. And to do that need to do
some hackery to lose all the other headers.
=> expose client sent headers

package.json, src/generate-types.ts, test/example.yaml
output scalars with branding. We still accept unbranded values though as otherwise we would need to convert stuff deep inside some shapes which would be a pita.
=> Branded scalars

yarn.lock
- Bump union-value from 1.0.0 to 1.0.1 to update set-value from 2.0.0 to 2.0.1
- also cleanup unneeded duplicates from yarn.lock (`yarn-deduplicate yarn.lock`)
=> bump union-value from 1.0.0 to 1.0.1 and yarn-deduplicate

src/generate-types.ts
now we use the normalized property name in the required list
=> handle required path params correctly

adapters/koa/koa.ts
If the request body is an array, it's converted into an object in the validation. Thus having an api endpoint like the following fails validation
```
content:
application/json:
schema:
type: array
items:
$ref: '#/components/schemas/Item'
```
Workaround is to have something like the following, but wrapping the array into an object is kinda weird endpoint imho
```
content:
application/json:
schema:
type: object
properties:
items:
$ref: '#/components/schemas/Items'
required:
- items
```
=> do not convert request body into object if it's an array

README.md, adapters/koa/koa.ts, adapters/koa/package.json, examples/server.ts, package.json, runtime/package.json, runtime/src/client.ts, runtime/src/server.ts, runtime/test/server.spec.ts, src/generate-server.ts, test/example.yaml, yarn.lock
Adds support for being able to provide request context to endpoint
handlers. Introduces new type `EndpointWithContext<RequestContext>`,
and changes Koa adapter to allow extracting data from koa context as
request context for the OpenAPI endpoints.
=> Support request context for handlers in server side

.github/workflows/nodejs.yml, build-all.sh, package.json, runtime/package.json, runtime/src/reflection-type.ts, runtime/src/runtime.ts, runtime/src/value-class.ts, runtime/yarn.lock, src/generate-types.ts, yarn.lock
add runtime type info for values so that we can type strings and generate values
todo
solves https://github.com/smartlyio/oats/issues/40
=> Include reflectable types

src/driver.ts
**Motivation**
I have `Module1` where I want to import openapi from `Module2`. Currently I can do it by relative path to `node_modules` and it works pretty fine. But after that I want to import openapi from `Module1` to `Module3`. And `Module2` installs as dependency of `Module2` in subfolder `node_modules`
```
/node_modules
/Module1
/node_modules
/Module2
```
and when I try to build my `Module3` relative path starts to point on a wrong place in `node_modules` structure.
**My suggestion here**: allow using of installed modules names as root instead of relative path by setting `isInstalledModule` option. In this case module will not be resolved with relative path and we build types with imports from installed modules in `node_modules`.
Probably having additional flag is a little bit dirty …
=> Don't resolve installed modules

README.md, README.template.md, package.json, src/generate-types.ts, src/util.ts, test/codegen.spec.ts, test/common.yaml
split nullable classes to 'null | NonNullableSomeClass'
the class cannot be nullable as it needs to be a proper js class so we need to do some hackery. This fixes https://github.com/smartlyio/oats/issues/58 about constructing empty objects from nullable
The downside is that we end up with ugly NonNullableSomeClass for the actual class which also might break some existing code relying on `instanceof SomeClass`
=> Nullable bug

src/generate-types.ts, test/codegen.spec.ts, test/common.yaml
I need type in smartly-actions with flag `enabled: boolean`. By this flag I want to choose what type to use: no additional fields for `false` and to required fields for `true`. Current oats implementation threats boolean enum as string. This PR contains fix
=> Fix bool enums

package.json, test/optional-queries/api.yml, test/optional-queries/optional-queries.spec.ts, yarn.lock
use oats-runtime 2.7.3 to ensure that the body in a client request is required (when it actually should be there)
=> Fix require body when it is required

.gitignore, package.json, src/generate-types.ts, test/example.yaml, yarn.lock
It would look something like this and would allow us to access the header properties that are declared in the openapi spec
```ts
{
readonly status: 201;
readonly value: {
readonly contentType: "application/json";
readonly value: common.ShapeOfItem;
};
readonly headers: {
readonly location: string;
};
}
```
https://github.com/smartlyio/oats-runtime/pull/106
https://github.com/smartlyio/oats-axios-adapter/pull/42
=> Add reponse headers property

package.json, src/generate-types.ts, test/codegen.spec.ts, test/common.yaml, test/example.yaml, yarn.lock
Generates separate makeOneOfWithDiscriminator if discriminator
configuration is specified for oneOf. This allows make to home into
correct maker immediately without trying all the options, which improves
performance a lot.
With Caesar actions the difference was:
```
Before
makeAction x 2,624 ops/sec ±1.85% (86 runs sampled)
After
makeAction x 342,554 ops/sec ±1.74% (85 runs sampled)
```
Requires https://github.com/smartlyio/oats-runtime/pull/127. Will need to
bump version numbers once that is in.
=> Add support for discriminator in oneOf

index.ts, package.json
For `oats-generator` project we need `Resolve` type from `generate-types` which is not exported now, so we use type `driver.Driver['resolve']` which is kinda OK-ish, but it's type also contains `undefined` which is not true in our use-case there, so we do ugly `!` at the end of function call to tell TypeScript that it should be always with a `Resolve` type.
So may we can export `generate-types` and use Resolve type directly?
=> Export generate-types as well

package.json, src/generate-types.ts, yarn.lock
https://github.com/smartlyio/oats-runtime/pull/143
either `oats-runtime` or `oats` is going to be have to be merged with failing CI since this change breaks both 😅
=> ShapeOf is no longer necessary

src/generate-types.ts, src/status-codes.ts, test/example.yaml, test/status-codes.spec.ts
see https://swagger.io/specification/
fixes https://github.com/smartlyio/oats/issues/211
=> allow wildcard overlap with literal status code

packages/oats-runtime/src/union-discriminator.ts, packages/oats-runtime/test/make-from-reflection.spec.ts
when we had nested oneofs where the leaf oneOfs children some had properties usable for tagging and some did not  (ie some children had enum props and some did not) we ended up throwing because typescript is a lie
=> fix throw when child union had untagged members

CHANGELOG.md, packages/oats-koa-adapter/README.md, packages/oats-koa-adapter/README.template.md, packages/oats-koa-adapter/index.ts, test/koa-adapter/koa-adapter.spec.ts
- change signature of koa adapter bind to be named arguments as the there are already a bunch of arguments
- allow passing a list of middlewares that get applied to all endpoints defined in bind `spec` (note: not all possible endpoints just the one you have defined a handler for)
=> allow passing middlewares to koa router endpoints

CHANGELOG.md, packages/oats-fast-check/src/generator.ts, packages/oats-runtime/src/make.ts, packages/oats-runtime/src/reflection-type.ts, packages/oats-runtime/src/union-discriminator.ts, packages/oats-runtime/src/value-class.ts, packages/oats-runtime/test/make-from-reflection.spec.ts, packages/oats/src/generate-types.ts, test/cyclical-dependencies/cyclical.spec.ts, test/cyclical-dependencies/driver.ts, test/cyclical-dependencies/first.yaml, test/cyclical-dependencies/second.yaml, test/reflection/reflection-type.spec.ts
Get rid of Object.assign and use functions for references instead.
should fix #140 
released as `@4.0.0-alpha.2` for testing
=> Support cyclical dependencies

CHANGELOG.md, packages/oats/src/driver.ts, packages/oats/src/generate-types.ts, test/no-default-emit-undefined/api.yml, test/no-default-emit-undefined/driver.ts, test/no-default-emit-undefined/no-emit-undefined-index.spec.ts
ts has option to do that better now so might make sense to move to use
that instead when needed
=> add option to avoid emitting undefined union type for index signatures

packages/oats/src/driver.ts, packages/oats/src/generate-types.ts, test/no-emit-unknown-index/api.yml, test/no-emit-unknown-index/driver.ts, test/no-emit-unknown-index/no-emit-unknown-index.spec.ts
`additionalproperties: true` results in `[key:string]: unknown` signatures in objects. This is tedious if the additional prop is there to allow non-breaking migrations. Lets allow omitting the unknow signatures.
=> add option to omit unknown index type for additionalProperties

package.json, packages/oats-koa-adapter/index.ts, packages/oats-runtime/.npmrc, packages/oats-runtime/package.json, packages/oats-runtime/src/redirect.ts, packages/oats-runtime/src/runtime.ts, packages/oats-runtime/src/server.ts, packages/oats-runtime/test/redirect.spec.ts, test/koa-adapter/api.yml, test/koa-adapter/koa-adapter.spec.ts
This implements a "runtime.redirect()" helper. It returns the same "server.Response" object, but checks for redirect status and sets Location header.
=> AETHER-2101 implement runtime redirect

CHANGELOG.md
Note, I do not mention runtime.redirect() since we write changelogs only for the things that can raise questions.
=> add changelogs for koa adapter fix

packages/oats/src/generate-server.ts
Generate types as:
```ts
export type EndpointsWithContext<RequestContext> = {
readonly "/item"?: {
readonly "post": oar.server.Endpoint<types.Headers$Item$Post, types.Parameters$Item$Post, types.Query$Item$Post, types.RequestBody$Item$Post, types.ShapeOfResponse$Item$Post, RequestContext>;
};
readonly "/item/{id}"?: {
readonly "get": oar.server.Endpoint<types.Headers$Item$Id$Get, types.Parameters$Item$Id$Get, types.Query$Item$Id$Get, types.RequestBody$Item$Id$Get, types.ShapeOfResponse$Item$Id$Get, RequestContext>;
readonly "head": oar.server.Endpoint<types.Headers$Item$Id$Head, types.Parameters$Item$Id$Head, types.Query$Item$Id$Head, types.RequestBody$Item$Id$Head, types.ShapeOfResponse$Item$Id$Head, RequestContext>;
readonly "delete": oar.server.Endpoint<types.Headers$Item$Id$Delete, …
```
=> Generate enpoints as types instead of interfaces

CHANGELOG.md, packages/oats-runtime/package.json, packages/oats-runtime/src/redirect.ts, packages/oats-runtime/test/redirect.spec.ts
Turned out `encodeURI` does double encoding of already encoded params. Both koa and express are using `encodeurl` package in their redirect implementation.
=> fix: use encodeurl instead of encodeURI

packages/oats-mirage-adapter/index.ts
- Adds boolean parameter `logging` to Mirage adapter.
- The parameter can be used to control logging from within adapter.
=> Allow developer to disable logging from mirage adapter

packages/oats/src/generate-types.ts
generated class after this change:
```ts
export class Error extends oar.valueClass.ValueClass {
readonly message!: string;
readonly messageIndex!: number;
// @ts-ignore tsc does not like unused privates
readonly #__oats_value_class_brand_tag!: string;
readonly [instanceIndexSignatureKey: string]: unknown;
public constructor(value: ShapeOfError, opts?: oar.make.MakeOptions | InternalUnsafeConstructorOption) { super(); oar.instanceAssign(this, value, opts, buildError); }
public static reflection: oar.reflection.NamedTypeDefinitionDeferred<Error> = () => { return typeError; };
static make(value: ShapeOfError, opts?: oar.make.MakeOptions): oar.make.Make<Error> { const make = buildError(value, opts); if (make.isError())
return oar.make.Make.error(make.errors);
else
return oar.make.Make.ok(new …
```
=> Make oats tag truly private

packages/oats-runtime/src/make.ts, packages/oats-runtime/test/make-from-reflection.spec.ts
in case additionalProperties: false we did not drop undefined props like we planned. Now we do.
=> actually drop undefined for unknown additionalprops

package.json, packages/oats-fast-check/package.json, packages/oats-nock-adapter/package.json, packages/oats-nock-adapter/test/server.spec.ts, packages/oats-runtime/package.json, packages/oats-runtime/src/client.ts, packages/oats-runtime/src/make.ts, packages/oats-runtime/src/server.ts, packages/oats/package.json, packages/oats/src/generate-server.ts, packages/oats/src/generate-types.ts, packages/oats/src/util.ts, test/reflection/reflection-type.spec.ts
If one header is defined the generated type is:
```ts
readonly headers: {
readonly etag: string;
readonly [key: string]: string | undefined;
};
```
but if no header is the defined the type is:
```ts
readonly headers: {};
```
with this PR the generated type if no headers are defined will be:
```ts
readonly headers: {
readonly [key: string]: string | undefined;
};
```
which, in my opinion, is the expected behaviour given the first scenario
=> If no headers are defined, generate type as `Record<string, string|undefined>`

packages/oats-fetch-adapter/index.ts, test/fetch-adapter/api.yml, test/fetch-adapter/fetch-adapter.spec.ts
We're turning arrays into strings wrong when parsing query parameters
=> Fix oats fetch adapter

packages/oats-runtime/src/client.ts, packages/oats-runtime/src/server.ts, packages/oats/package.json, packages/oats/src/generate-server.ts, test/request-parsing/api.yml, test/request-parsing/client-body.spec.ts, test/request-parsing/driver.ts, test/request-parsing/server-body.spec.ts
Clients of `client` & `server` implementations can define what to do with unknown fields; to throw error or just drop fields.
=> Add body make options for client & server so clients can define how to handle values

packages/oats-runtime/src/make.ts, test/request-parsing/api.yml, test/request-parsing/client-body.spec.ts, test/request-parsing/server-body.spec.ts
This wouldn't be backwards compatible change as now we are loosening validation with "drop". 
Earlier we would have thrown an error (which some clients might be depending at the moment, hopefully not) if input matched multiple schemas with "drop" option. Now the behaviour would change to first check which object had the most matched properties and use it.
If multiple matched objects has the same amount of matched properties, we can't identify the best match and return the same error as earlier `multiple options match`
=> Change drop option to behave the same way 'fail' would when matching to schema

packages/oats-runtime/src/client.ts, packages/oats-runtime/src/server.ts, test/request-parsing/api-out-of-sync.yml, test/request-parsing/api.yml, test/request-parsing/client-body-receive.spec.ts, test/request-parsing/client-body-send.spec.ts, test/request-parsing/driver.ts
Currently client can't drop additional properties even though client is created with:
```ts
client.createClient({
validationOptions: { body: { unknownField: 'drop' } }
})
```
Lets fix that, and let client also drop additional properties from server responses.
This currently works for:
* client sending request
* server receiving request
but was missing from client receiving response from the server.
=> Add possibility drop additional properties when client is handling response from server

packages/oats-fetch-adapter/index.ts
this way one can configure `fetch` more granularly
=> Allow passing `init` to base fetch

packages/oats-fetch-adapter/index.ts, test/fetch-adapter/api.yml, test/fetch-adapter/fetch-adapter.spec.ts
turns out `fetch` is case-insensitive for the `PATCH` method, so let's set all methods to always be upper case
https://github.com/github/fetch/issues/254
=> Fix calling PATCH with fetch

packages/oats-fetch-adapter/index.ts
fetch doesn't return a body on `HEAD` calls. and overall we shouldn't try to parse one if there isn't one to parse 🤷
=> Dont try to parse a body if there isn't one

packages/oats-axios-adapter/index.ts, packages/oats-fetch-adapter/index.ts, packages/oats-runtime/src/client.ts, packages/oats-runtime/src/server.ts, packages/oats-runtime/test/client.spec.ts, test/fetch-adapter/fetch-adapter.spec.ts
**What?**
Allow passing `AbortController.signal` to oats axios / fetch adapters.
=> Support abort signal

CHANGELOG.md, packages/oats-runtime/src/make.ts, packages/oats-runtime/test/make-from-reflection.spec.ts, test/property-name-mapping/api.yml, test/property-name-mapping/property-name-mapper.spec.ts
Bug fix for network mapping when a value was made with different makers. 
```
const value = Amake(input).success();
const value2 = Bmake(value).success();
```
value2 had both A and B types and network mapping tried to use mapping also from A type when it should have only used mappings from type B if any.
Now value2 does not have a linkage anymore to type A and will not be considered when network mapping. 
Note: because value2 does not have type A anymore any `getType` or `getTypeSet` reflection calls will return different
results to what was previously returned.
There may be a performance downside to this as we might end up doing extra work as we lose the type information. 
Even without doing double `.make` by hand allOf parsing may result in more work being done as we clear the extra …
=> fix incorrect network mapping when values are made more than once

packages/oats-fetch-adapter/index.ts, test/fetch-adapter/api.yml, test/fetch-adapter/fetch-adapter.spec.ts
Now we have an issue with oats-fetch-adapter, that the runtime validation fails for the response with the error like: 
```
invalid response body /workspaces/{workspaceId} no option of oneOf matched - option 1 value: no option of oneOf matched - option 1 value: expected value to be one of , but got "" instead.
```
I am not sure how to test the implementation locally, but I believe based on the logic that it happens because:
1. The content type identifies incorrectly here: https://github.com/smartlyio/oats/blob/master/packages/oats-fetch-adapter/index.ts#L36
2. The response returns incorrectly here as ""(empty string) instead of `null` https://github.com/smartlyio/oats/blob/master/packages/oats-fetch-adapter/index.ts#L45
I faced the problem in this PR for frontend …
=> Handle noContentType correctly for fetch adapter

packages/oats-runtime/src/make.ts, packages/oats-runtime/src/server.ts
Helps distinguish OpenAPI errors in logs, Sentry, and other places that rely on the name property. 
Because there was no custom name in the first place, I don't expect any client code to rely on it.
=> Add name field to runtime error subclasses

packages/oats/src/generate-types.ts
Extremely minor, but also extremely annoying, generator output is filled with import resolve logging, which is not needed every time you generate stuff.
With this PR, these messages will be hidden by default, but could be enabled back with `NODE_DEBUG=oats`. This is a simple and standard way to handle these things in node
Before
After
=> Make import resolve logging optional

packages/oats-axios-adapter/index.ts
[form-data](https://www.npmjs.com/package/form-data) is used only on Node. if its run on the browser, it will switch to the window's version of FormData. Library code:
`module.exports = typeof self == 'object' ? self.FormData : window.FormData`
For that reason we are getting the above error while making a `multipart/form-data` type request.
=> Fix `data.getHeaders is not a function` issue

packages/oats-runtime/package.json, packages/oats-runtime/src/make.ts
Buffer is node specific api which causes trouble when trying to use oats-runtime in browser. 
* use feross/buffer which has separate entrypoints for node (using node Buffer) and browser (using a lookalike)
* remove the typescript reference from make.d.ts that includes node types
canary release @7.5.1-alpha.11
=> import Buffer from buffer

packages/oats/src/driver.ts, packages/oats/src/generate-server.ts, packages/oats/src/util.ts, packages/oats/test/include-endpoints.spec.ts
Implements `includeEndpoints` driver option to generate code only for the given endpoints.
=> includeEndpoints-driver-option

packages/oats-nock-adapter/src/nock.ts
Fixes the header issue in https://github.com/smartlyio/unity/pull/1484 tests
=> Fix / Add response headers to nock reply in adapterForServer in oats-nock-adapter
