.prettierrc
index.ts
package.json
src/driver.ts
src/generate-server.ts
src/generate-types.ts
src/runtime.ts
src/server.ts
test/driver.spec.ts
tslint.json
yarn.lock

Noticed that there was no standard lint style, or the shortcut command for linting. So I created both and ran it against the existing files.
Also moved prettier to the `devDependencies` section. I believe it belongs there...

Add prettier and lint

---

.github/workflows/nodejs.yml

Run tests and TypeScript build on relevant Node.js versions.

Setup CI using GitHub Actions

---

package.json
src/generate-types.ts
src/runtime.ts

union with empty enum allows assignment to number for string & brand. this is not cool

better branding

---

package.json
runtime/package.json
runtime/src/make.ts
yarn.lock

As it is now, we have to look at the logs to figure out what the actual value is. This should save us some time.

Return value in err msg

---

package.json
src/generate-types.ts

ts seems to lose the type of the brand from the compiled d.ts files when the
fields are private. So: add the field to the valueclass itself as then ts considers things to not be assignable.

fix branding

---

package.json
src/generate-types.ts
test/common.yaml
yarn.lock

see https://github.com/smartlyio/oats-runtime/pull/7

emit pattern for strings

---

README.md
examples/driver.ts
src/driver.ts
src/generate-server.ts
src/generate-types.ts
src/util.ts
test/example-with-security-nodes.yaml

This isn't there yet, there's a bunch of duplication and verbosity that I'm going to try and break down a bit further.
I also have to add the test scenario we talked about earlier (I can't find the conversation but trust me, I think I remember what words were more or less used...)
Closes #54

Allowing consumers to ignore unsupported features

---

package.json
renovate.json
yarn.lock

i'll update the other oats libs too

Unpin libs

---

examples/driver.ts
package.json
src/driver.ts
src/generate-types.ts

making paths relative breaks imports from node_modules. As this is all very
confusing add info logging to tell what we are doing.

do not make paths relative by force

---

package.json
src/generate-types.ts
test/optional-queries/api.yml
test/optional-queries/driver.ts
test/optional-queries/optional-queries.spec.ts
tsconfig.json
yarn.lock

fixes #147
mainly by using https://github.com/smartlyio/oats-runtime/pull/94

fix optional query params throwing in server

---

package.json
src/driver.ts

this is nice when adding eslint ignores to the files

add header to client and server files

---

package.json
src/generate-types.ts
yarn.lock

depends on https://github.com/smartlyio/oats-runtime/pull/122

Check array/number bounds

---

.github/workflows/nodejs.yml
package.json
src/generate-types.ts

```yml
something:
type: string
enum:
- toot
- doot
- noot
```
```ts
Object.assign(typeSomething, {
name: "Something",
definition: {
type: "string",
enum: ["toot", "doot", "noot"]
},
maker: makeSomething,
isA: (value: any) => makeSomething(value).isSuccess()
})
```

generate "isA" for scalars

---

src/generate-types.ts

Update:
Now with 100% less breakage but same performance improvements. Preserve constructor, but add one internal option to sidestep build and use provided results.
Original message
createMakerWith tried creating new object with constructor and catching
the errors. When used inside oneOf it lead to constant throwing of
exceptions with isn't great for performance.
This commit introduces breaking change in that generated class
constructors are private, and only means of creating class is via make.
Make will use build function for creating the data, and only creating
new object if the built was successful. This allows us pass errors in
one of case without attempted creation of object and throwing the error.
With Goya benchmark following changes were observed.
Before:
```
makeAd with simple …
```

Optimize parsing speed by reducing reliance on exceptions

---

packages/oats-fast-check/jest.config.js

Same as https://github.com/smartlyio/platform-sdk/pull/37
(Sorry, I just worry it's gonna spread via copypaste all over the org 😅)

Remove copy-pasted bit from jest.config.js

---

packages/oats-runtime/src/make.ts
test/property-name-mapping/api.yml
test/property-name-mapping/property-name-mapper.spec.ts

allOf with nested objects did not serialize properly due to additionalprops: true losing the type

propagate types through any even with surprising clone

---

CHANGELOG.md
packages/oats/src/driver.ts
packages/oats/src/generate-types.ts
test/exploding-queries/api.yml
test/exploding-queries/query.spec.ts

see changelog
canary at 7.4.4-alpha.2

allow multiple non-objects with explode true

---

packages/oats/package.json
packages/oats/src/generate-types.ts
test/negative-limits/driver.ts
test/negative-limits/fixture.yaml

ts 544 has assertion for dealing with negative numbers in ast. Construct the ast correctlier.

handle negative numbers correctly

---

packages/oats-runtime/src/make.ts
packages/oats-runtime/src/reflection-type.ts

As per our discussion in Slack ([thread](https://smartlyio.slack.com/archives/C013HRMK693/p1712589245528449?thread_ts=1712325741.910979&cid=C013HRMK693)), tried to add support of MDN File type as Binary.

Add support for web file type

---

packages/oats-runtime/src/make.ts
packages/oats-runtime/src/reflection-type.ts

Revert "Add support for web file type"
